package sbnz.integracija;

import sbnz.integracija.example.model.Patient;
import sbnz.integracija.example.model.enums.PhysicalActivity;


rule "Pulse Limit - VERY ACTIVE Physical Activity"
	agenda-group "set-pulse-limit"
    when
        $i: Patient( physicalActivity == PhysicalActivity.VERY_ACTIVE)
    then
    	System.out.println("Pulse Limit set for VERY ACTIVE pa");
        $i.setBottomPulse((((220 - $i.getAge()) - 70) * 78) + 70);
        $i.setUpperPulse((((220 - $i.getAge()) - 70) * 90) + 70);
        update($i);
end

rule "Pulse Limit - MODERATE Physical Activity"
	agenda-group "set-pulse-limit"
    when
        $i: Patient( physicalActivity == PhysicalActivity.MODERATE )
    then
        System.out.println("Pulse Limit set for MODERATE pa");
        $i.setBottomPulse((((220 - $i.getAge()) - 70) * 64) + 70);
        $i.setUpperPulse((((220 - $i.getAge()) - 70) * 77) + 70);
        update($i);
end

rule "Pulse Limit - SEDENTARY Physical Activity"
	agenda-group "set-pulse-limit"
    when
        $i: Patient( physicalActivity == PhysicalActivity.SEDENTARY)
    then
    	System.out.println("Pulse Limit set for SEDENTARY pa");
        $i.setBottomPulse((((220 - $i.getAge()) - 70) * 50) + 70);
        $i.setUpperPulse((((220 - $i.getAge()) - 70) * 63) + 70);
        update($i);
end